# [ lvm_volume - tasks/lvm_set_lvol.yaml ]

- lvg:
    pvs: "{{ lvm_pvs_devices | join(',') }}"
    vg: "{{ lvm_lvg_name }}"

- lvol:
    vg: "{{ lvm_lvg_name }}"
    lv: "{{ item }}"
    size: "{{ lvm_lvol_size }}"
    resizefs: yes
  with_items: "{{ lvm_lvol_full_names }}"

- filesystem:
    dev: "{{ item }}"
    fstype: "{{ lvm_lvol_filesystem_fstype }}"
    opts: "{{ lvm_lvol_filesystem_opts }}"
  with_items: "{{ lvm_lvol_devices }}"
  when: not ansible_check_mode


# Set mount directory
- block:
  - name: Set mount directory
    file:
      path: "{{ item }}"
      recurse: yes
      state: directory
    with_items: "{{ lvm_lvol_paths }}"

  - file:
      path: "{{ item }}"
      recurse: no
      state: directory
      owner: "{{ lvm_lvol_mount_path_owner }}"
      group: "{{ lvm_lvol_mount_path_group }}"
      mode: "{{ lvm_lvol_mount_path_mode }}"
    with_items: "{{ lvm_lvol_paths }}"


# Mount LVM volume
- name: Mount LVM volume
  mount:
    src: "{{ item.split(':')[0] }}"
    path: "{{ item.split(':')[1] }}"
    fstype: "{{ lvm_lvol_filesystem_fstype }}"
    opts: "{{ lvm_lvol_mount_opts }}"
    state: mounted
  with_items: "{{ lvm_lvol_mounts }}"
