# [ lvm_volume - tasks/lvm_set_lvol.yaml ]

- package:
    name: "{{ lvm_packages }}"
    state: present
  notify: daemon-reload

- lvg:
    pvs: "{{ lvm_pvs_devices | join(',') }}"
    vg: "{{ lvm_lvg_name }}"

- lvol:
    vg: "{{ lvm_lvg_name }}"
    lv: "{{ item }}"
    size: "{{ lvm_lvol_size }}"
    resizefs: yes
  with_items: "{{ lvm_lvol_full_names }}"

- filesystem:
    dev: "{{ item }}"
    fstype: "{{ lvm_lvol_filesystem_fstype }}"
    opts: "{{ lvm_lvol_filesystem_opts }}"
  with_items: "{{ lvm_lvol_devices }}"

- file:
    path: "{{ item }}"
    recurse: yes
    state: directory
    owner: root
    group: root
    mode: 0755
  changed_when: no
  with_items: "{{ lvm_lvol_paths }}"

- mount:
    src: "{{ item.split(':')[0] }}"
    path: "{{ item.split(':')[1] }}"
    fstype: "{{ lvm_lvol_filesystem_fstype }}"
    opts: "{{ lvm_lvol_mount_opts }}"
    state: mounted
  with_items: "{{ lvm_lvol_mounts }}"
