# [ lvm_volume - tasks ]

# Check mandatory variables
- name: Check mandatory variables
  ansible.builtin.assert:
    that: lvm_lvol_suffix != ''
    quiet: true
    msg: "Mandatory variables have to be defined (lvol: {{ lvm_lvol_paths_str }})!"
  run_once: true
  when: (lvm_lvol_replicas | int) > 1
  tags: [ always ]


# Preview of LVM volume
- name: Preview of LVM volume
  ansible.builtin.debug:
    msg:
      - "lvm_lvol_full_names:      {{ lvm_lvol_full_names }}"
      - "lvm_lvol_size:            {{ lvm_lvol_size }}"
      - "lvm_lvol_devices:         {{ lvm_lvol_devices }}"
      - "lvm_lvol_paths:           {{ lvm_lvol_paths }}"
  run_once: true
  tags: [ never, get-lvm_lvol_preview ]


# Remove LVM volume
- name: Remove LVM volume
  ansible.builtin.include_tasks:
    file: "roles/{{ role_name }}/tasks/lvm_remove_lvol.yml"
    apply:
      tags: always
  tags: [ never, remove-lvm_lvol ]


# Set LVM volume
- name: Set LVM volume
  ansible.builtin.include_tasks:
    file: "roles/{{ role_name }}/tasks/lvm_set_lvol.yml"
    apply:
      tags: always
  when:
    - lvm_pvs_devices != []
  tags: [ set-lvm_lvol ]
